"""init

Revision ID: 74d4d9cf158f
Revises: 
Create Date: 2026-03-24 14:43:59.231074

"""
from typing import Sequence, Union
import os

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import uuid
from datetime import datetime, timezone

# revision identifiers, used by Alembic.
revision: str = '74d4d9cf158f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('created', 'params_received', 'audio_uploaded', 'processing', 'partially_completed', 'completed', 'failed', name='process_status'), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    operations = table(
        'operations',
        column('id', sa.UUID),
        column('status', sa.String),
        column('created_at', sa.DateTime),
        column('updated_at', sa.DateTime),
    )

    op.bulk_insert(
        operations,
        [
            {
                "id": uuid.UUID(os.getenv("TEST_OPERATION_ID")),
                "status": "created",
                "created_at": datetime.now(timezone.utc),
                "updated_at": datetime.now(timezone.utc),
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    # ### end Alembic commands ###
