"""init

Revision ID: 74d4d9cf158f
Revises: 
Create Date: 2026-03-24 14:43:59.231074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
import uuid
from datetime import datetime, timezone

# revision identifiers, used by Alembic.
revision: str = '74d4d9cf158f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.UUID(), default=uuid.uuid4, nullable=False),
        sa.Column('status', sa.Enum('created', 'params_received', 'audio_uploaded',
                                    'processing', 'partially_completed', 'completed',
                                    'closed', 'failed', 'cancelled', 'cancelling', name='process_status'),
                  nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),

        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('operation_versions',
                    sa.Column('id', sa.UUID(), primary_key=True, default=uuid.uuid4),
                    sa.Column('operation_id', sa.UUID(), sa.ForeignKey('operations.id'), nullable=False),

                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),

                    sa.ForeignKeyConstraint(['operation_id'],
                                            ['operations.id'],
                                            ondelete='CASCADE'),

                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('recognize_tasks',
    sa.Column('id', sa.UUID(), primary_key=True, default=uuid.uuid4),
        sa.Column('operation_id', sa.UUID(), sa.ForeignKey('operations.id'), nullable=False),
        sa.Column('version_id', sa.UUID(), sa.ForeignKey('operation_versions.id'), nullable=False),

        sa.Column('file_s3_key', sa.String(), nullable=False),
        sa.Column('status', sa.Enum('pending', 'queued', 'processing', 'done', 'failed',
                                name='task_status'), nullable=False),
        sa.Column('params', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),

        sa.ForeignKeyConstraint(['operation_id'],
                                ['operations.id'],
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['version_id'],
                                ['operation_versions.id'],
                                ondelete='CASCADE'),

        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('llm_tasks',
    sa.Column('id', sa.UUID(), primary_key=True, default=uuid.uuid4),
        sa.Column('operation_id', sa.UUID(), sa.ForeignKey('operations.id'), nullable=False),

        sa.Column('version_id', sa.UUID(), sa.ForeignKey('operation_versions.id'), nullable=False),
        sa.Column('transcript_s3_key', sa.String(), nullable=False),
        sa.Column('frames_key', sa.String(), nullable=True),
        sa.Column('status', sa.Enum('pending', 'queued', 'processing', 'done', 'failed',
                                name='task_status'), nullable=False),
        sa.Column('params', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),

        sa.ForeignKeyConstraint(['operation_id'],
                                ['operations.id'],
                                ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['version_id'],
                                ['operation_versions.id'],
                                ondelete='CASCADE'),

        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(
        "uq_one_active_version_per_op",
        "operation_versions",
        ["operation_id"],
        unique=True,
        postgresql_where="is_active = true",
    )

    operations = table(
        'operations',
        column('id', sa.UUID),
        column('status', sa.String),
        column('created_at', sa.DateTime),
        column('updated_at', sa.DateTime)
    )

    op.bulk_insert(
        operations,
        [
            {
                "id": uuid.UUID("736d3b0d-c553-4936-876c-24a751b758de"),
                "status": "created",
                "created_at": datetime.now(timezone.utc),
                "updated_at": datetime.now(timezone.utc),
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    # ### end Alembic commands ###
